have error - Table 'cinema.movie' doesn't exist
Fedich09/cinema-hibernate pull request #1
Opened 2021-01-26 15:19 UTC by Fedich09

2021-01-26 16:31 UTC, Ketch92 approved these changes

2021-01-26 16:31 UTC, Ketch92 commented on .gitignore
> +*.log
Github says: add an empty line man

2021-01-26 16:31 UTC, Ketch92 commented on src/main/java/com/dev/cinema/model/Movie.java
> +    }
можу запропонувати додати equals i hashcode

2021-01-26 16:38 UTC, Sofasmile requested changes

2021-01-26 16:38 UTC, Sofasmile commented on .gitignore
> +*.log
add empty line

2021-01-26 16:38 UTC, Sofasmile commented on src/main/java/com/dev/cinema/dao/impl/MovieDaoImpl.java
> +            throw new DataProcessingException("Can't insert Movie entity ", e);
```suggestion
            throw new DataProcessingException("Can't insert Movie entity " + movie, e);
```

2021-01-27 07:09 UTC, Sofasmile approved these changes

2021-01-27 11:06 UTC, merged