Spring 8
Fedich09/cinema-hibernate pull request #10
Opened 2021-02-21 15:20 UTC by Fedich09

2021-02-21 15:48 UTC, NikolayFatkullin approved these changes

2021-02-22 09:03 UTC, RomanDubovskyi requested changes

2021-02-22 09:03 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/dao/impl/UserDaoImpl.java
> +                            + "left join fetch u.roles WHERE u.email = :email",
use inner join here, all users should have roles

2021-02-22 09:03 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/dbinit/InjectData.java
> +        user.setPassword(securityConfig.getEncoder().encode("admin"));
password should be encoded in the UserService

2021-02-22 09:03 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/model/User.java
> +    @ManyToMany(fetch = FetchType.LAZY)
it's lazy by default

2021-02-22 11:56 UTC, RomanDubovskyi requested changes

2021-02-22 11:56 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.GET).permitAll()
is user allowed to perform complete order ?(it's POST)

2021-02-22 11:56 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/service/impl/UserServiceImpl.java
> +    private final AppConfig appConfig;
inject Encoder here instead of Appconfig (it's a bean as well)

2021-02-22 12:46 UTC, RomanDubovskyi approved these changes
improve requests permissions according to Sofia's message in general chat

2021-02-22 12:46 UTC, RomanDubovskyi commented on src/main/java/com/dev/cinema/config/SecurityConfig.java
> +                .antMatchers(HttpMethod.POST, "/orders/complete").hasRole("USER")
adding product to shopping cart is not GET as well

2021-02-22 12:58 UTC, merged