Readme
Fedich09/cinema-hibernate pull request #11
Opened 2021-02-25 19:05 UTC by Fedich09

2021-02-25 19:09 UTC, Artificial-Friend requested changes

2021-02-25 19:09 UTC, Artificial-Friend commented on src/main/java/com/dev/operaapp/controller/PerformanceController.java
> +    private final PerformanceMapperImpl movieMapperImpl;
` movieMapperImpl`

2021-02-25 19:09 UTC, Artificial-Friend commented on src/main/java/com/dev/operaapp/dao/PerformanceSessionDao.java
> +    List<PerformanceSession> findAvailableSessions(Long movieId, LocalDate date);
`movieId`

2021-02-25 19:23 UTC, Artificial-Friend approved these changes

2021-02-25 19:23 UTC, Artificial-Friend commented on src/main/java/com/dev/operaapp/controller/PerformanceController.java
> +    private final PerformanceMapperImpl movieMapperImpl;
!!!

2021-02-25 19:23 UTC, Artificial-Friend commented on src/main/java/com/dev/operaapp/controller/PerformanceController.java
> +                .map(movieMapperImpl::toDto)
w

2021-02-26 06:57 UTC, Sofasmile commented on README.md
> +6. db.url=jdbc:mysql://localhost/*your_db_name*?serverTimezone=EET
це не зовсім пункти, це більше підпункти до Setup connection properties in **db.properties** file

2021-02-26 06:57 UTC, Sofasmile commented on README.md
> +##Author
```suggestion
## Author
```

2021-02-26 15:26 UTC, Sofasmile approved these changes
можеш мержити ПР і повидаляй зайві гілки на гітхабі)

2021-02-26 15:27 UTC, merged