hb-5
Fedich09/cinema-hibernate pull request #3
Opened 2021-02-02 14:09 UTC by Fedich09

2021-02-02 14:14 UTC, NikolayFatkullin approved these changes

2021-02-02 17:12 UTC, dmytro-hryhoruk requested changes

2021-02-02 17:12 UTC, dmytro-hryhoruk commented on src/main/java/com/dev/cinema/security/impl/AuthenticationServiceImpl.java
> +                        + "email or password not exist in the db "));
let's not say explicitly which part of the credentials was wrong. Let's refactor this method, so we are throwing exception only in one place with message: Wrong email or password; You may just combine checks

2021-02-02 17:12 UTC, dmytro-hryhoruk commented on src/main/java/com/dev/cinema/util/HashUtil.java
> +
```suggestion
```

2021-02-03 11:37 UTC, dmytro-hryhoruk approved these changes

2021-02-03 11:38 UTC, merged