added and implemented models: Ticket, ShoppingCart; dao: ShoppingCart…
Fedich09/cinema-hibernate pull request #4
Opened 2021-02-03 14:34 UTC by Fedich09

…Dao, TicketDao, ShoppingCartDaoImpl, TicketDaoImpl; service: ShoppingCatService, ShippingCartServiceImpl and cnaged register method in AuthenticationServiceImpl, also added usage in Main class, main method

2021-02-03 16:17 UTC, NikolayFatkullin approved these changes

2021-02-03 16:17 UTC, NikolayFatkullin commented on src/main/java/com/dev/cinema/dao/impl/ShoppingCartDaoImpl.java
> +            throw new DataProcessingException("Can't create shopping cart " + shoppingCart, e);
```suggestion
            throw new DataProcessingException("Can't update shopping cart " + shoppingCart, e);
```
I guess it would be better =)

2021-02-03 23:21 UTC, Fedich09 commented on src/main/java/com/dev/cinema/dao/impl/ShoppingCartDaoImpl.java
> +            throw new DataProcessingException("Can't create shopping cart " + shoppingCart, e);
agree )

2021-02-04 07:48 UTC, KseniiaMakarova requested changes

2021-02-04 07:48 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/ShoppingCart.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
do we need this?

2021-02-04 07:48 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/model/Ticket.java
> +    @JoinColumn(name = "movie_session")
```suggestion
    @JoinColumn(name = "movie_session_id")
```

2021-02-04 09:13 UTC, KseniiaMakarova approved these changes
let's fix travis

2021-02-04 10:30 UTC, merged